name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk git \
          libffi-dev libssl-dev libgmp-dev m4 gfortran \
          pkg-config autoconf automake libtool build-essential \
          gettext libltdl-dev

    - name: Fix libtool macros (LT_SYS_SYMBOL_USCORE)
      run: |
        echo "m4_pattern_allow([LT_SYS_SYMBOL_USCORE])" >> configure.ac || true
        libtoolize --force --copy || true
        aclocal || true
        autoheader || true
        autoconf || true
        automake --add-missing || true

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv python-for-android

    - name: Clean previous build cache
      run: rm -rf .buildozer bin

    - name: Configure buildozer (single arch for faster build)
      run: |
        sed -i 's/^android.arch = .*/android.arch = arm64-v8a/' buildozer.spec
    
    - name: Save .buildozer logs if build fails
      if: failure()
      run: |
        mkdir -p logs
        find .buildozer -name "*.log" -exec cp --parents {} logs \; || true
        cp -r .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds logs/full_build_logs || true
    
    - name: Output Buildozer Log Summary
      if: failure()
      run: |
        echo "::group::Buildozer Log Tail"
        tail -n 200 .buildozer/android/platform/build-arm64-v8a/build/other_builds/*/*/*.log || true
        echo "::endgroup::"


    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: buildozer-logs
        path: logs

    - name: Build APK
      run: buildozer android debug --log-level 2

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
