name: Build Kivy APK (No Artifact Upload)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip \
          libtool libffi-dev build-essential autoconf automake
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Build APK
      run: |
        buildozer android debug

    - name: Encode APK to base64
      run: |
        echo "==== APK base64 begin ===="
        base64 -w 0 bin/*.apk
        echo "==== APK base64 end ===="
