name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize buildozer.spec if missing
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Fix permissions (optional)
      run: |
        chmod +x ./main.py || true

    - name: Build APK
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip openjdk-17-jdk
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: fftapp-debug-apk
        path: bin/*.apk
