name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk git \
          libffi-dev libssl-dev libgmp-dev m4 gfortran \
          pkg-config autoconf automake libtool build-essential \
          gettext libltdl-dev

    - name: Fix libtool macros (LT_SYS_SYMBOL_USCORE)
      run: |
        if grep -q 'LT_SYS_SYMBOL_USCORE' configure.ac; then
          echo 'm4_pattern_allow([LT_SYS_SYMBOL_USCORE])' | cat - configure.ac > temp && mv temp configure.ac
        fi
        libtoolize --force --copy || true
        aclocal || true
        autoheader || true
        autoconf || true
        automake --add-missing || true

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython virtualenv python-for-android

    - name: Clean .buildozer
      run: rm -rf .buildozer

    - name: Build APK with logs to console
      run: buildozer android debug --log-level 2
      env:
        P4A_RELEASE_KEYSTORE_PASS: ''
        P4A_RELEASE_KEYALIAS_PASS: ''
        P4A_RELEASE_KEYALIAS: ''
        P4A_RELEASE_KEYSTORE: ''
          

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
