name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk git \
          libffi-dev libssl-dev libgmp-dev m4 gfortran \
          pkg-config autoconf automake libtool libtool-bin \
          gettext libltdl-dev

    - name: Patch libtool macros (LT_SYS_SYMBOL_USCORE)
      run: |
        sudo cp /usr/share/aclocal/libtool.m4 /usr/share/aclocal-1.16/ || true
        sudo cp /usr/share/aclocal/lt*.m4 /usr/share/aclocal-1.16/ || true
        libtoolize --install || true

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython virtualenv python-for-android

    - name: Clean previous builds
      run: rm -rf .buildozer bin

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-app
        path: bin/*.apk
