name: Build Kivy APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          zip unzip openjdk-17-jdk python3-pip libtool libffi-dev \
          build-essential autoconf automake

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Initialize buildozer (first time only)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Build the APK
      run: |
        buildozer android debug

    - name: Upload APK to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: fftapp-apk
        path: bin/*.apk
